version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: punkpay
      POSTGRES_PASSWORD: punkpay_dev
      POSTGRES_DB: punkpay
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U punkpay']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 128mb --maxmemory-policy noeviction --requirepass ""
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M

  signal-cli:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      MODE: normal
    ports:
      - '8080:8080'
    volumes:
      - signal-cli-config:/home/.local/share/signal-cli
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  pgdata:
  redisdata:
  signal-cli-config:
